### ISSUE TITLE
How to get poller result for LRO polling

### ISSUE THREAD

**Issue by Rahulnigam28** [lmazuel/azure-sdk-for-python#80]
Is there any way to handle poller results  separately ?
I am running invoke-azurermvmruncommand and then getting the object as a variable.
It is a  msrest.polling.poller.LROPoller object  . I am able to call result method on that object and get the value of result.

I am trying to pass this object to another function and then get the output separately. For that I am first converting this object into dict using .__dict__ method and then passing it to another function.
How can I convert this object back to class so I can query for result method ?

**Comment by lmazuel** [comment]
Hi @Rahulnigam28 
That's my personal fork, and not the official repo :)
Please open an issue at https://github.com/Azure/azure-sdk-for-python/issues
